name: wemake-python

on:
  - push
  - pull_request

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
        pip install pytest
    - name: Run linter and pytest
      run: |
        make lint
        make test
